apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: registry

resources:
  - namespace.yaml
  - pvc.yaml
  - ingress.yaml
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: registry-auth
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true
