apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clustersecret

resources:
  - namespace.yaml

secretGenerator:
  - name: cloudflare-api-creds-root
    envs:
      - .env
  - name: docker-registry-auth
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson

commonAnnotations:
  reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik,cert-manager,kube-system,local-services,quotes"
  reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "traefik,cert-manager,kube-system,local-services,quotes"

generatorOptions:
  disableNameSuffixHash: true
