apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
resources:
- namespace.yaml
- dnsendpoint.yaml

secretGenerator:
  - name: plex-claim-secret
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true