---
# Ingress for Unifi
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi
  namespace: local-services
  annotations:
    external-dns.alpha.kubernetes.io/hostname: unifi.stevearnett.com
    external-dns.alpha.kubernetes.io/target: kube.stevearnett.com
    traefik.ingress.kubernetes.io/service.serverstransport: insecure-transport@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - unifi.stevearnett.com
    secretName: wildcard-stevearnett-com-tls
  rules:
  - host: unifi.stevearnett.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unifi-local
            port:
              number: 443
