apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-services

resources:
  - namespace.yaml
  - serverstransport.yaml
  - service-nas.yaml
  - service-zb.yaml
  - service-unifi.yaml
  - ingress-nas.yaml
  - ingress-zb.yaml
  - ingressroute-unifi.yaml
