apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  configuration.yaml: |
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 192.168.1.96
    mobile_app:
    wemo:
      discovery: true
    homeassistant:
      customize:
        # Unhide specific pool size sensors (replace with actual entity IDs)
        sensor.ugreen_dxp2800_d460_pool_1:
          hidden: false
        sensor.ugreen_xp2800_d460_pool_2:
          hidden: false
