apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  configuration.yaml: |
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 192.168.1.96
    mobile_app:
    assist_pipeline:
    wemo:
      discovery: true
    history:
    homeassistant:
      time_zone: America/Los_Angeles
      customize:
        sensor.ugreen_dxp2800_d460_pool_1:
          hidden: false
        sensor.ugreen_xp2800_d460_pool_2:
          hidden: false
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
    rest: !include rests.yaml
