apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8123"
    prometheus.io/path: "/api/prometheus"
spec:
  ports:
    - port: 8123
  selector:
    app: home-assistant