apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - namespace.yaml
  - overseerr.yaml
  - readarr.yaml
  - prowlarr.yaml
  - radarr.yaml
  - sonarr.yaml
  - flaresolverr.yaml
  - lidarr.yaml
  - ingress-overseerr.yaml
  - ingress-readarr.yaml
  - ingress-prowlarr.yaml
  - ingress-radarr.yaml
  - ingress-sonarr.yaml
  - ingress-lidarr.yaml
  - dnsendpoint-lidarr.yaml
  #- bazarr.yaml?
