apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - namespace.yaml
  - overseerr.yaml
  - prowlarr.yaml
  - radarr.yaml
  - sonarr.yaml
  - flaresolverr.yaml
  - lidarr.yaml
  - ingress-jellyfin.yaml
