apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caddy-ingress
  namespace: caddy
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kube.stevearnett.com,auth.stevearnett.com,dashboard.kube.stevearnett.com,grafana.kube.stevearnett.com,prometheus.kube.stevearnett.com,ha.kube.stevearnett.com,qb.kube.stevearnett.com,prowlarr.kube.stevearnett.com,radarr.kube.stevearnett.com,sonarr.kube.stevearnett.com
spec:
  rules:
    - host: kube.stevearnett.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: auth.stevearnett.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: dashboard.kube.stevearnett.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: grafana.kube.stevearnett.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: prometheus.kube.stevearnett.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: ha.kube.stevearnett.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: qb.kube.stevearnett.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: prowlarr.kube.stevearnett.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: radarr.kube.stevearnett.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: sonarr.kube.stevearnett.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
