apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi
  namespace: caddy
  annotations:
    kubernetes.io/ingress.class: caddy
    external-dns.alpha.kubernetes.io/hostname: unifi.stevearnett.com
    external-dns.alpha.kubernetes.io/target: kube.stevearnett.com
    caddy.ingress.kubernetes.io/backend-protocol: https
    caddy.ingress.kubernetes.io/insecure-skip-verify: "true"
spec:
  tls:
  - hosts:
    - unifi.stevearnett.com
    secretName: wildcard-stevearnett-com-tls
  rules:
  - host: unifi.stevearnett.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unifi-local
            port:
              number: 443
