apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - local-services.yaml
  - ingress-local-devices.yaml
  - ingress-unifi.yaml
generatorOptions:
  disableNameSuffixHash: true
