apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: caddy
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2019"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 2019
      targetPort: 2019
  selector:
    app: caddy
