apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - namespace.yaml

secretGenerator:
  - name: oauth2-proxy-secret
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true
