apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik
  - cert-manager
  - oauth2-proxy
  - cluster-secrets
  - dashboard
  - monitoring
  - home-assistant
  - plex
  - media
  - vpn
  - cloudflared
  - speedtest
  - local-services
  - quotes
  - registry
  - kube-system/coredns-configmap-patch.yaml
  - renovate

