apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - oauth2-proxy
  - cluster-secrets
  - caddy
  - dashboard
  - monitoring
  - home-assistant
  - plex
  - media
  - vpn
  - cloudflared
  - kube-system/coredns-configmap-patch.yaml


